
# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ actions ]
  pull_request:
    branches: [ actions ]

jobs:
  compile:
   runs-on: ubuntu-latest
   name: Java 8 compile
   steps: 
     - uses: actions/cache@v2
     - name: Setup Java
       uses: actions/setup-java@v1
       with:
        java-version: 1.8
     - uses: actions/checkout@v2
     - run: mvn -B compile --file pom.xml
  build:
    runs-on: ubuntu-latest
    needs: compile
    steps:
    - uses: actions/cache@v2
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn -B package --file pom.xml
  itest:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/cache@v2
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
    - name: Run itests
      run: mvn -B package --file distribution/tests/itests/test-itests-ddf/pom.xml
